apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sendemail
spec:
  type: bindings.smtp
  version: v1
  metadata:
  - name: host
    value: localhost
  - name: port
    value: 1025
  - name: skipTLSVerify
    value: true