name: pubsub
extensions:
  - name: dapr
    components-path: "./components"
services:
  - name: publisher
    project: ./Publisher/Publisher.csproj
    bindings:
      - port: 2509
        protocol: http
  - name: subscriber
    project: ./Subscriber/Subscriber.csproj
    bindings:
      - port: 2511
        protocol: http
  - name: redis
    image: redis
    bindings:
      - port: 6379
        connectionString: "${host}:${port}"
  - name: rabbitmq
    image: rabbitmq:3-management
    bindings:
      - name: ui
        protocol: http
        port: 15672
        containerPort: 15672
      - name: amqp
        protocol: amqp
        port: 5672
        containerPort: 5672